<?php

namespace AppBundle\Repository;

/**
 * Invoice_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invoice_detailRepository extends \Doctrine\ORM\EntityRepository
{
}
